
/**
 * PANDUAN SQL SUPABASE:
 * Jalankan perintah ini di SQL Editor Supabase Anda:
 * 
 * CREATE TABLE nasabah (
 *   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 *   nama TEXT NOT NULL,
 *   usia INTEGER NOT NULL,
 *   pekerjaan TEXT NOT NULL,
 *   pendapatan_bulanan NUMERIC NOT NULL,
 *   tanggungan INTEGER NOT NULL,
 *   riwayat_kredit TEXT NOT NULL,
 *   jumlah_pembiayaan NUMERIC NOT NULL,
 *   agunan TEXT,
 *   lama_usaha INTEGER,
 *   status_approval TEXT,
 *   created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
 * );
 * 
 * ALTER TABLE nasabah ENABLE ROW LEVEL SECURITY;
 * CREATE POLICY "Public Access" ON nasabah FOR ALL USING (true);
 */

import React, { useState, useEffect } from 'react';
import PredictionForm from './components/PredictionForm';
import CustomerDataTable from './components/CustomerDataTable';
import StatisticsDashboard from './components/StatisticsDashboard';
import ModelPerformanceDashboard from './components/ModelPerformanceDashboard';
import DescriptiveAnalysis from './components/DescriptiveAnalysis';
import ReportPage from './components/ReportPage';
import { type Nasabah } from './types';
import { supabase, supabaseUrl } from './lib/supabase';
import { BrainCircuit, Dna, LayoutDashboard, Table, UserPlus, ClipboardPen, Menu, X, FileDown, Loader, ServerCrash } from 'lucide-react';

type Tab = 'prediksi' | 'dataNasabah' | 'statistik' | 'modelPerformance' | 'analisisDeskriptif' | 'laporan';

// Komponen Navigasi (Didefinisikan di luar agar tidak re-render)
const NavLink = ({ tabName, label, icon: Icon, isActive, onClick }: any) => (
  <li>
    <a
      href="#"
      onClick={(e) => { e.preventDefault(); onClick(tabName); }}
      className={`flex items-center p-3 rounded-lg transition-all duration-200 ${
        isActive ? 'bg-slate-700 text-white shadow-md' : 'text-slate-400 hover:bg-slate-800 hover:text-white'
      }`}
    >
      <Icon className="w-5 h-5 mr-3" />
      <span className="font-medium">{label}</span>
    </a>
  </li>
);

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>('prediksi');
  const [nasabahData, setNasabahData] = useState<Nasabah[]>([]);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const initData = async () => {
      setLoading(true);
      try {
        if (!supabaseUrl || supabaseUrl.includes('YOUR_PROJECT_ID')) {
          throw new Error('URL Supabase belum dikonfigurasi di lib/supabase.ts');
        }

        const { data, error: sbError } = await supabase
          .from('nasabah') // EKUIVALEN: supabase.table("nasabah")
          .select('*')
          .order('created_at', { ascending: false });

        if (sbError) throw sbError;
        setNasabahData((data as unknown as Nasabah[]) || []);
      } catch (err: any) {
        setError(err.message || 'Gagal memuat data dari database.');
      } finally {
        setLoading(false);
      }
    };
    initData();
  }, []);

  const handleSave = async (newNasabah: Nasabah) => {
    try {
      const { data, error } = await supabase
        .from('nasabah')
        .insert({ ...newNasabah, id: undefined })
        .select()
        .single();

      if (error) throw error;
      if (data) {
        setNasabahData(prev => [(data as unknown as Nasabah), ...prev]);
        setActiveTab('dataNasabah');
      }
    } catch (err: any) {
      alert(`Gagal menyimpan ke database: ${err.message}`);
    }
  };

  const TABS_CONFIG = {
    prediksi: { label: 'Prediksi AI', icon: UserPlus, component: <PredictionForm onPredictionSuccess={handleSave} /> },
    dataNasabah: { label: 'Database Nasabah', icon: Table, component: <CustomerDataTable nasabahData={nasabahData} /> },
    statistik: { label: 'Dashboard Visual', icon: LayoutDashboard, component: <StatisticsDashboard nasabahData={nasabahData} /> },
    modelPerformance: { label: 'Kinerja AI', icon: BrainCircuit, component: <ModelPerformanceDashboard allNasabahData={nasabahData} /> },
    analisisDeskriptif: { label: 'Analisis Data', icon: ClipboardPen, component: <DescriptiveAnalysis nasabahData={nasabahData} /> },
    laporan: { label: 'Laporan Akhir', icon: FileDown, component: <ReportPage allNasabahData={nasabahData} /> }
  };

  const renderActiveTab = () => {
    if (loading) return (
      <div className="flex flex-col items-center justify-center h-64 text-slate-400">
        <Loader className="animate-spin mb-4" size={40} />
        <p>Sinkronisasi data...</p>
      </div>
    );
    if (error) return (
      <div className="bg-red-50 border border-red-200 p-8 rounded-xl text-center max-w-xl mx-auto mt-10">
        <ServerCrash className="mx-auto text-red-500 mb-4" size={48} />
        <h3 className="text-red-800 font-bold text-lg">Masalah Koneksi</h3>
        <p className="text-red-600 mt-2 text-sm">{error}</p>
        <button onClick={() => window.location.reload()} className="mt-6 bg-red-600 text-white px-6 py-2 rounded-lg hover:bg-red-700 transition-colors">
          Coba Lagi
        </button>
      </div>
    );
    return TABS_CONFIG[activeTab].component;
  };

  return (
    <div className="min-h-screen bg-slate-50 flex text-slate-900">
      {/* Sidebar Overlay Mobile */}
      {sidebarOpen && <div className="fixed inset-0 bg-black/50 z-30 lg:hidden" onClick={() => setSidebarOpen(false)} />}

      {/* Sidebar - EKUIVALEN: st.sidebar */}
      <aside className={`fixed lg:relative inset-y-0 left-0 w-72 bg-slate-900 z-40 transform transition-transform duration-300 ease-in-out ${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} lg:translate-x-0 flex flex-col`}>
        <div className="p-6 flex items-center gap-3 border-b border-slate-800">
          <Dna className="text-indigo-500" size={32} />
          <div>
            <h1 className="text-white font-bold text-lg leading-tight">Syariah AI</h1>
            <p className="text-slate-500 text-xs uppercase tracking-widest">Analytics Pro</p>
          </div>
        </div>
        
        <nav className="flex-1 p-4 overflow-y-auto">
          <ul className="space-y-1">
            {Object.entries(TABS_CONFIG).map(([key, val]) => (
              <NavLink 
                key={key} 
                tabName={key} 
                label={val.label} 
                icon={val.icon} 
                isActive={activeTab === key} 
                onClick={(t: Tab) => { setActiveTab(t); setSidebarOpen(false); }} 
              />
            ))}
          </ul>
        </nav>
        
        <div className="p-6 border-t border-slate-800 text-center">
          <p className="text-slate-500 text-[10px]">&copy; 2024 Koperasi Digital v2.1</p>
        </div>
      </aside>

      {/* Main Area */}
      <div className="flex-1 flex flex-col min-w-0">
        <header className="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-6 sticky top-0 z-20">
          <div className="flex items-center">
            <button onClick={() => setSidebarOpen(true)} className="lg:hidden p-2 -ml-2 text-slate-500 hover:bg-slate-100 rounded-md">
              <Menu size={24} />
            </button>
            <h2 className="text-lg font-bold text-slate-800 ml-2 lg:ml-0">
              {TABS_CONFIG[activeTab].label}
            </h2>
          </div>
          <div className="flex items-center gap-2">
            <div className="hidden sm:block text-right">
              <p className="text-xs font-bold text-slate-900">Admin Panel</p>
              <p className="text-[10px] text-teal-600 font-medium">System Online</p>
            </div>
            <div className="h-8 w-8 rounded-full bg-slate-200 flex items-center justify-center text-slate-500 font-bold text-xs border border-slate-300">
              AD
            </div>
          </div>
        </header>

        <main className="flex-1 p-4 md:p-8 overflow-x-hidden">
          <div className="max-w-6xl mx-auto">
            {renderActiveTab()}
          </div>
        </main>
      </div>
    </div>
  );
};

export default App;
